package com.mycompany.demabitespresentacion;

import com.mycompany.demabitesdominio.Comanda;
import control.ComandasControl;
import java.util.List;
import java.util.logging.Logger;
import utileria.utilMetodos;

/**
 *
 * @author Emily Lara
 * 270719
 */
public class FrameComandas extends javax.swing.JFrame {

    private final ComandasControl control; // Instanciamos el control
    private static final Logger LOGGER = java.util.logging.Logger.getLogger(FrameComandas.class.getName());
    
    public FrameComandas() {
        initComponents();
        this.control = new ComandasControl();
        cargarComandas();
        ocultarColumnaId();
        MenuHeader header = new MenuHeader();
        utilMetodos.insertarPanel(pnlHeader, header);
    }
    
    private void cargarComandas() {
        List<Comanda> lista = control.cargarTablaComandas();
        llenarTabla(lista); 
    }
    
    
    private void ocultarColumnaId() {
        tablaComandas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaComandas.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaComandas.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlComandas = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        pnlTablaComandas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComandas = new javax.swing.JTable();
        txtConsultar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlDetallesComanda = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();
        lbl2 = new javax.swing.JLabel();
        btnNuevaComanda = new javax.swing.JButton();
        btnEntregarComanda = new javax.swing.JButton();
        btnCancelarComanda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 255, 234));
        setPreferredSize(new java.awt.Dimension(1200, 675));

        pnlComandas.setBackground(new java.awt.Color(254, 255, 234));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        lbl1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 32)); // NOI18N
        lbl1.setForeground(new java.awt.Color(52, 59, 27));
        lbl1.setText("Comandas");

        tablaComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Folio", "Mesa", "Cliente", "Fecha", "Estado", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaComandas);

        javax.swing.GroupLayout pnlTablaComandasLayout = new javax.swing.GroupLayout(pnlTablaComandas);
        pnlTablaComandas.setLayout(pnlTablaComandasLayout);
        pnlTablaComandasLayout.setHorizontalGroup(
            pnlTablaComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        pnlTablaComandasLayout.setVerticalGroup(
            pnlTablaComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaComandasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        txtConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConsultar.setForeground(new java.awt.Color(204, 204, 204));
        txtConsultar.setText("Ingrese folio, cliente o mesa...");
        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(47, 65, 86));
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Cantidad", "Comentario", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tablaDetalles);

        javax.swing.GroupLayout pnlDetallesComandaLayout = new javax.swing.GroupLayout(pnlDetallesComanda);
        pnlDetallesComanda.setLayout(pnlDetallesComandaLayout);
        pnlDetallesComandaLayout.setHorizontalGroup(
            pnlDetallesComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetallesComandaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDetallesComandaLayout.setVerticalGroup(
            pnlDetallesComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        lbl2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 28)); // NOI18N
        lbl2.setForeground(new java.awt.Color(52, 59, 27));
        lbl2.setText("Detalles de la comanda");

        btnNuevaComanda.setBackground(new java.awt.Color(25, 56, 64));
        btnNuevaComanda.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnNuevaComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaComanda.setText("Nueva comanda");
        btnNuevaComanda.setToolTipText("");
        btnNuevaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaComandaActionPerformed(evt);
            }
        });

        btnEntregarComanda.setBackground(new java.awt.Color(47, 65, 86));
        btnEntregarComanda.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnEntregarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnEntregarComanda.setText("Entregar");
        btnEntregarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarComandaActionPerformed(evt);
            }
        });

        btnCancelarComanda.setBackground(new java.awt.Color(158, 42, 43));
        btnCancelarComanda.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnCancelarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarComanda.setText("CANCELAR");
        btnCancelarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComandasLayout = new javax.swing.GroupLayout(pnlComandas);
        pnlComandas.setLayout(pnlComandasLayout);
        pnlComandasLayout.setHorizontalGroup(
            pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlComandasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComandasLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTablaComandas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlComandasLayout.createSequentialGroup()
                        .addGroup(pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDetallesComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNuevaComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(btnEntregarComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pnlComandasLayout.setVerticalGroup(
            pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComandasLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTablaComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlComandasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDetallesComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlComandasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnNuevaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEntregarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultar(txtConsultar.getText().trim());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaComandaActionPerformed

    private void btnEntregarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntregarComandaActionPerformed

    private void btnCancelarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarComandaActionPerformed

    private void consultar(String filtro) {
        List<Comanda> listaFiltrada = control.filtrar(filtro);
        llenarTabla(listaFiltrada); // Llenamos la tabla con lo que encontró el control
    }
    
    // Método de apoyo para no repetir código al llenar la tabla
    private void llenarTabla(List<Comanda> lista) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaComandas.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de agregar los nuevos datos
        
        // Formato para que la fecha se vea bien
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        
        for (Comanda c : lista) {
            String mesaStr = (c.getMesa() != null) ? "Mesa " + c.getMesa().getNumero() : "S/N";
            String clienteStr = "Cliente General";
            if (c.getCliente() != null) {
                clienteStr = c.getCliente().getNombres() + " " + c.getCliente().getApellidoPaterno();
            }
            String fechaStr = c.getFechaHora().format(formatter);
            
            // Agregamos la fila respetando el orden de tus columnas en el diseño
            modelo.addRow(new Object[]{
                c.getId(),
                c.getFolio(),
                mesaStr,
                clienteStr,
                fechaStr,
                c.getEstado(),
                String.format("$%.2f", c.getTotal())
            });
        }
        
        // Como reiniciamos el modelo, hay que asegurar que la columna ID siga oculta
        ocultarColumnaId(); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarComanda;
    private javax.swing.JButton btnEntregarComanda;
    private javax.swing.JButton btnNuevaComanda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JPanel pnlComandas;
    private javax.swing.JPanel pnlDetallesComanda;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTablaComandas;
    private javax.swing.JTable tablaComandas;
    private javax.swing.JTable tablaDetalles;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
