package com.mycompany.demabitespresentacion;

import Enums.Tipo;
import com.mycompany.demabitesdominio.Producto;
import control.Navegacion;
import control.ProductosControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utileria.utilMetodos;

/**
 *
 * @author Dario
 */
public class FrameProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameProductos.class.getName());
    
    private final ProductosControl control;

    /**
     * Creates new form FrameProductos
     */
    public FrameProductos() {
        initComponents();
        this.control = new ProductosControl();
        llenarTabla();
        MenuHeader header = new MenuHeader();
        utilMetodos.insertarPanel(pnlHeader, header);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        pnlTablaProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnEditarProducto = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();
        btnCambiarEstadoProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(254, 255, 234));

        pnlHeader.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        lbl1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 32)); // NOI18N
        lbl1.setForeground(new java.awt.Color(52, 59, 27));
        lbl1.setText("Productos");

        jScrollPane1.setFont(jScrollPane1.getFont().deriveFont(jScrollPane1.getFont().getSize()+20f));

        tblProductos.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setRowHeight(30);
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout pnlTablaProductosLayout = new javax.swing.GroupLayout(pnlTablaProductos);
        pnlTablaProductos.setLayout(pnlTablaProductosLayout);
        pnlTablaProductosLayout.setHorizontalGroup(
            pnlTablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        pnlTablaProductosLayout.setVerticalGroup(
            pnlTablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaProductosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnBuscar.setBackground(new java.awt.Color(47, 65, 86));
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnNuevoProducto.setBackground(new java.awt.Color(47, 65, 86));
        btnNuevoProducto.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.setToolTipText("");
        btnNuevoProducto.addActionListener(this::btnNuevoProductoActionPerformed);

        lbl4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl4.setForeground(new java.awt.Color(52, 59, 27));
        lbl4.setText("Consultar por nombre o tipo");

        txtBuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnEditarProducto.setBackground(new java.awt.Color(47, 65, 86));
        btnEditarProducto.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProducto.setText("Editar Producto");
        btnEditarProducto.setActionCommand("Editar Producto");
        btnEditarProducto.addActionListener(this::btnEditarProductoActionPerformed);

        cbxTipo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel(new Object[] { "---", Tipo.PLATILLO, Tipo.BEBIDA, Tipo.POSTRE }));

        btnCambiarEstadoProducto.setBackground(new java.awt.Color(47, 65, 86));
        btnCambiarEstadoProducto.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnCambiarEstadoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarEstadoProducto.setText("Cambiar Estado Producto");
        btnCambiarEstadoProducto.setToolTipText("");
        btnCambiarEstadoProducto.addActionListener(this::btnCambiarEstadoProductoActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnBuscar))
                                    .addComponent(lbl4)))
                            .addComponent(pnlTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnNuevoProducto)
                        .addGap(136, 136, 136)
                        .addComponent(btnEditarProducto)
                        .addGap(106, 106, 106)
                        .addComponent(btnCambiarEstadoProducto)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscar))
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(48, 48, 48)))
                .addComponent(pnlTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoProducto)
                    .addComponent(btnEditarProducto)
                    .addComponent(btnCambiarEstadoProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        Navegacion.getControlNavegacion().abrirProductosForm();
        dispose();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        consultar();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        seleccionarProductoEditar();
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnCambiarEstadoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoProductoActionPerformed
        seleccionarProductoCambiarEstado();
    }//GEN-LAST:event_btnCambiarEstadoProductoActionPerformed

    /**
    * Oculta la columna del ID para que no sea visible al usuario pero siga existiendo en el modelo.
    */
   public void ocultarColumnaID() {
        if (tblProductos.getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setMinWidth(0);
            tblProductos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(0);
        }
   }

   /**
    * Llena la tabla de productos activos.
    */
   private void llenarTabla() {
       DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
       modelo.setRowCount(0);

       List<Producto> lista = control.cargarTabla();

       for (Producto producto : lista) {
           Object[] fila = new Object[5];
           fila[0] = producto.getId();
           fila[1] = producto.getNombre();
           fila[2] = producto.getDescripcion();
           fila[3] = producto.getPrecio();
           fila[4] = producto.getTipoProducto();
           modelo.addRow(fila);
       }
       ocultarColumnaID();
   }

   /**
    * Filtra los productos por nombre y categoria.
    */
    private void consultar() {
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        String filtro = txtBuscar.getText().trim();
        Tipo tipo = null;
        if (cbxTipo.getSelectedIndex() > 0) {
            String nombreEnum = cbxTipo.getSelectedItem().toString();
            tipo = Tipo.valueOf(nombreEnum); 
        }

        List<Producto> lista = control.filtrar(filtro, tipo, this);

        for (Producto producto : lista) {
            Object[] fila = new Object[5];
            fila[0] = producto.getId();
            fila[1] = producto.getNombre();
            fila[2] = producto.getDescripcion();
            fila[3] = producto.getPrecio();
            fila[4] = producto.getTipoProducto();
            modelo.addRow(fila);
        }
        ocultarColumnaID();
    }

   /**
    * Obtiene el ID seleccionado y abre la pantalla de edicion.
    */
    private void seleccionarProductoEditar() {
        int fila = tblProductos.getSelectedRow();
        if (fila != -1) {
            int filaModelo = tblProductos.convertRowIndexToModel(fila);
            Object valorId = tblProductos.getModel().getValueAt(filaModelo, 0);
            Long idProducto = Long.valueOf(valorId.toString());
            Navegacion.getControlNavegacion().setDato(idProducto);
            Navegacion.getControlNavegacion().abrirEditarProductosForm();
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un producto de la tabla.");
        }
    }
   
   /**
    * Obtiene el ID seleccionado y cambia el estado de su producto.
    */
    private void seleccionarProductoCambiarEstado() {
        int fila = tblProductos.getSelectedRow();
        if (fila != -1) {
            int filaModelo = tblProductos.convertRowIndexToModel(fila);
            Object valorId = tblProductos.getModel().getValueAt(filaModelo, 0); 
            Long idProducto = Long.valueOf(valorId.toString());
            control.cambiarEstado(idProducto, this);
            llenarTabla(); 
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un producto de la tabla.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarEstadoProducto;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTablaProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
