/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demabitespresentacion;

import control.Navegacion;

/**
 *
 * @author Jesus Omar
 */
public class FrameInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicioSesion
     */
    public FrameInicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMesero = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 255, 234));

        btnMesero.setBackground(new java.awt.Color(47, 65, 86));
        btnMesero.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        btnMesero.setForeground(new java.awt.Color(255, 255, 255));
        btnMesero.setText("SOY MESERO");
        btnMesero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMeseroMouseClicked(evt);
            }
        });

        btnAdministrador.setBackground(new java.awt.Color(47, 65, 86));
        btnAdministrador.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrador.setText("SOY ADMINISTRADOR");
        btnAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdministradorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdministrador)
                    .addComponent(btnMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnMesero)
                .addGap(101, 101, 101)
                .addComponent(btnAdministrador)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradorMouseClicked
        Navegacion navegador = Navegacion.getControlNavegacion();
        navegador.setRol("ADMIN");
        navegador.abrirMenuPrincipal();
    }//GEN-LAST:event_btnAdministradorMouseClicked

    private void btnMeseroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeseroMouseClicked
        Navegacion navegador = Navegacion.getControlNavegacion();
        navegador.setRol("MESERO");
        navegador.abrirMenuPrincipal();
    }//GEN-LAST:event_btnMeseroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnMesero;
    // End of variables declaration//GEN-END:variables
}
