package com.mycompany.demabitespresentacion;

import com.mycompany.demabitesdominio.ClienteFrecuente;
import control.ClientesControl;
import control.Navegacion;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utileria.utilMetodos;

/**
 * Interfaz grafica para la visualizacion y gestion de Clientes Frecuentes.
 * @author Dario
 */
public class FrameClientes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameClientes.class.getName());
    private final ClientesControl control;

    /**
     * Contructor del Frame.
     */
    public FrameClientes() {
        initComponents();
        this.control = new ClientesControl();
        llenarTabla();
        MenuHeader header = new MenuHeader();
        utilMetodos.insertarPanel(pnlHeader, header);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        pnlTablaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnEditarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(254, 255, 234));

        pnlHeader.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        lbl1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 32)); // NOI18N
        lbl1.setForeground(new java.awt.Color(52, 59, 27));
        lbl1.setText("Clientes ");

        jScrollPane1.setFont(jScrollPane1.getFont().deriveFont(jScrollPane1.getFont().getSize()+20f));

        tblClientes.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Teléfono", "Correo", "Puntos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setRowHeight(30);
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout pnlTablaClientesLayout = new javax.swing.GroupLayout(pnlTablaClientes);
        pnlTablaClientes.setLayout(pnlTablaClientesLayout);
        pnlTablaClientesLayout.setHorizontalGroup(
            pnlTablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        pnlTablaClientesLayout.setVerticalGroup(
            pnlTablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnBuscar.setBackground(new java.awt.Color(47, 65, 86));
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnNuevoCliente.setBackground(new java.awt.Color(47, 65, 86));
        btnNuevoCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(this::btnNuevoClienteActionPerformed);

        lbl4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl4.setForeground(new java.awt.Color(52, 59, 27));
        lbl4.setText("Consultar por nombre, teléfono o correo: ");

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnEditarCliente.setBackground(new java.awt.Color(47, 65, 86));
        btnEditarCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.addActionListener(this::btnEditarClienteActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnBuscar))
                            .addComponent(lbl4)))
                    .addComponent(pnlTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoCliente)
                .addGap(114, 114, 114)
                .addComponent(btnEditarCliente)
                .addGap(372, 372, 372))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuscar))
                        .addGap(24, 24, 24))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(48, 48, 48)))
                .addComponent(pnlTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente)
                    .addComponent(btnEditarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Redirige al usuario a otra pantalla para crear un cliente nuevo.
     * @param evt Evento de accion del boton.
     */
    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {
        Navegacion.getControlNavegacion().abrirClientesForm();
        this.dispose();
    }
    
    /**
     * Ejecuta la busqueda de clientes.
     * @param evt Evento de accion del boton.
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultar(txtBuscar.getText().trim());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        llenarTabla();
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * Ejecuta el metodo seleccionarClienteEditar.
     * @param evt Evento de accion del boton.
     */
    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        Navegacion.getControlNavegacion().abrirEditarClientesForm();
        this.dispose();
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    /**
     * Oculta la columna ID para que no se vea en el sistema
     * Este funcion sirve para hacer mas facil las tareas de 
     * manipulacion de clientes sin comprometer el ID de estos.
     */
    public void ocultarColumnaID() {
        if (tblClientes.getColumnCount() > 0) {
            tblClientes.removeColumn(tblClientes.getColumnModel().getColumn(0));
        }
    }
    
    /**
     * Llena la tabla de clientes registrados en el sistema.
     */
    private void llenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);
                                                                    
        List<ClienteFrecuente> lista = control.cargarTabla();

        Object[] fila = new Object[5]; 

        for (ClienteFrecuente cliente : lista) {
            fila[0] = cliente.getId(); 
            fila[1] = cliente.getNombres();
            fila[2] = cliente.getTelefono();
            fila[3] = (cliente.getEmail() == null || cliente.getEmail().isEmpty()) 
                        ? "sin correo" : cliente.getEmail();
            fila[4] = 0; // Puntos

            modelo.addRow(fila);
        }
        ocultarColumnaID();
    }

    /**
     * Llena la tabla conforme el resultado del filtro de consulta.
     * @param filtro String con el texto filtro.
     */
    private void consultar(String filtro) {
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);

        List<ClienteFrecuente> lista = control.filtrar(filtro, this);

        Object[] fila = new Object[5]; 

        for (ClienteFrecuente cliente : lista) {
            fila[0] = cliente.getId();
            fila[1] = cliente.getNombres();
            fila[2] = cliente.getTelefono();
            fila[3] = (cliente.getEmail() == null || cliente.getEmail().isEmpty()) 
                        ? "sin correo" : cliente.getEmail();
            fila[4] = 0;

            modelo.addRow(fila);
        }
        ocultarColumnaID();
    }
    
    /**
     * Conforme a la seleccion del cliente en la tabla, redirige al usuario
     * a otra pantalla para la edicion del cliente seleccionado.
     */
    private void seleccionarClienteEditar(){
        int fila = tblClientes.getSelectedRow();
            if (fila != -1) {
                int filaModelo = tblClientes.convertRowIndexToModel(fila);
                Object valorId = tblClientes.getModel().getValueAt(filaModelo, 0); 
                Long idCliente = Long.valueOf(valorId.toString());
                Navegacion.getControlNavegacion().setDato(idCliente);
                Navegacion.getControlNavegacion().abrirEditarClientesForm();
            }else{
                JOptionPane.showMessageDialog(this, "Por favor, selecciona un cliente de la tabla.");
            }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTablaClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
