package com.mycompany.demabitespresentacion;

import com.mycompany.demabitesdominio.Ingrediente;
import control.IngredientesControl;
import control.Navegacion;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus Omar
 */
public class IngredientesForm extends javax.swing.JFrame {

    private final IngredientesControl control;
    private List<Ingrediente> listaIngredientes;

    /**
     * Creates new form IngredientesForm
     */
    public IngredientesForm() {
        initComponents();
        this.control = new IngredientesControl();
        this.listaIngredientes = control.cargarTablaIngredientes();
        llenarTabla(this.listaIngredientes);
        tablaIngredientes.getColumnModel().getColumn(3).setCellRenderer(new Renderizador());
        MenuHeader menuHeader = new MenuHeader();
        menuHeader.setVisible(true);
        pnlHeader.setLayout(new BorderLayout());
        pnlHeader.add(menuHeader, BorderLayout.NORTH);
        pnlHeader.revalidate();
        pnlHeader.repaint();
    }

    private void llenarTabla(List<Ingrediente> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tablaIngredientes.getModel();
        modelo.setRowCount(0);

        if (lista == null) {
            return;
        }

        Object[] fila = new Object[4];

        for (Ingrediente i : listaIngredientes) {
            fila[0] = i.getNombre();
            fila[1] = i.getUnidad();
            fila[2] = i.getStock();

            byte[] bytesImagen = i.getImagenIngrediente();

            if (bytesImagen != null && bytesImagen.length > 0) {
                ImageIcon iconoOriginal = new ImageIcon(bytesImagen);
                Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(-1, 50, Image.SCALE_SMOOTH);
                fila[3] = new ImageIcon(imagenEscalada);
            } else {
                fila[3] = null;
            }

            modelo.addRow(fila);
        }

// IMPORTANTE: Dale más altura a las filas para que se vea la imagen
        tablaIngredientes.setRowHeight(50); // Mismo alto que escalamos la imagen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblIngredientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngredientes = new javax.swing.JTable();
        btnNuevoIngrediente = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 255, 234));

        pnlPrincipal.setBackground(new java.awt.Color(254, 255, 234));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1200, 699));

        pnlHeader.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        lblIngredientes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 32)); // NOI18N
        lblIngredientes.setText("Ingredientes");

        tablaIngredientes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        tablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Unidad", "Stock", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaIngredientes);
        if (tablaIngredientes.getColumnModel().getColumnCount() > 0) {
            tablaIngredientes.getColumnModel().getColumn(0).setResizable(false);
            tablaIngredientes.getColumnModel().getColumn(1).setResizable(false);
            tablaIngredientes.getColumnModel().getColumn(2).setResizable(false);
        }

        btnNuevoIngrediente.setBackground(new java.awt.Color(47, 65, 86));
        btnNuevoIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnNuevoIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoIngrediente.setText("Nuevo Ingrediente");
        btnNuevoIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoIngredienteMouseClicked(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(47, 65, 86));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(47, 65, 86));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblIngredientes)
                        .addGap(268, 268, 268)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoIngrediente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngredientes)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoIngrediente)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoIngredienteMouseClicked
        FormularioIngredientes formIngredientes = new FormularioIngredientes(this, true);
        formIngredientes.setTitle("Registrar Ingrediente");
        formIngredientes.setLocationRelativeTo(null);
        formIngredientes.setVisible(true);
        this.listaIngredientes = control.cargarTablaIngredientes();
        llenarTabla(this.listaIngredientes);
    }//GEN-LAST:event_btnNuevoIngredienteMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        int fila = tablaIngredientes.getSelectedRow();
        if (fila != -1) {
            Ingrediente ingredienteSeleccionado = listaIngredientes.get(fila);
            FormularioIngredientes formIngredientes = new FormularioIngredientes(this, true);
            formIngredientes.cargarDatosEdicion(ingredienteSeleccionado);
            formIngredientes.setLocationRelativeTo(null);
            formIngredientes.setVisible(true);
            this.listaIngredientes = control.cargarTablaIngredientes();
            llenarTabla(this.listaIngredientes);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un ingrediente");
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String filtro = txtBuscar.getText();
        this.listaIngredientes = control.buscarIngredientes(filtro);
        llenarTabla(listaIngredientes);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int fila = tablaIngredientes.getSelectedRow();
        if (fila != -1) {
            Ingrediente ingredienteSeleccionado = listaIngredientes.get(fila);
            Long id = ingredienteSeleccionado.getId();
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "Seguro que quieres eliminar este producto?"
                    + "" + ingredienteSeleccionado.getNombre()
                    + "" + ingredienteSeleccionado.getUnidad()
            );
            if (respuesta == JOptionPane.YES_OPTION) {
                control.eliminarIngrediente(id, this);
                this.listaIngredientes = control.cargarTablaIngredientes();
                llenarTabla(this.listaIngredientes);
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoIngrediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tablaIngredientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
