package com.mycompany.demabitespresentacion;

import control.Navegacion;

/**
 * Componente de interfaz de usuario JPanel que representa 
 * el menu de navegacion / header de la aplicacion.
 * @author Dario
 */
public class MenuHeader extends javax.swing.JPanel {

    /**
     * Contructor del Frame.
     */
    public MenuHeader() {
        initComponents();
        String pantallaActiva = Navegacion.getControlNavegacion().getPantallaActual();
        bloquearBotonActual(pantallaActiva);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        btnComandas = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        pnlHeader.setBackground(new java.awt.Color(255, 239, 150));

        lbl2.setFont(new java.awt.Font("Script MT Bold", 1, 56)); // NOI18N
        lbl2.setForeground(new java.awt.Color(158, 42, 43));
        lbl2.setText("DemaBites");

        btnComandas.setBackground(new java.awt.Color(255, 239, 150));
        btnComandas.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnComandas.setText("Comandas");
        btnComandas.setBorder(null);
        btnComandas.addActionListener(this::btnComandasActionPerformed);

        btnProductos.setBackground(new java.awt.Color(255, 239, 150));
        btnProductos.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(this::btnProductosActionPerformed);

        btnIngredientes.setBackground(new java.awt.Color(255, 239, 150));
        btnIngredientes.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnIngredientes.setText("Ingredientes");
        btnIngredientes.setBorder(null);
        btnIngredientes.addActionListener(this::btnIngredientesActionPerformed);

        btnClientes.setBackground(new java.awt.Color(255, 239, 150));
        btnClientes.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnReportes.setBackground(new java.awt.Color(255, 239, 150));
        btnReportes.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl2)
                .addGap(68, 68, 68)
                .addComponent(btnComandas)
                .addGap(53, 53, 53)
                .addComponent(btnProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnIngredientes)
                .addGap(32, 32, 32)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(btnComandas)
                    .addComponent(btnProductos)
                    .addComponent(btnIngredientes)
                    .addComponent(btnClientes)
                    .addComponent(btnReportes))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ejecuta la navegacion hacia el modulo de clientes.
     * @param evt Evento de accion del boton.
     */
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Navegacion.getControlNavegacion().abrirClientesFrame();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasActionPerformed
        Navegacion.getControlNavegacion().abrirComandasFrame();
    }//GEN-LAST:event_btnComandasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        Navegacion.getControlNavegacion().abrirFrameIngredientes();
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * Deshabilita el boton de navegacion que coincida con la pantalla actual.
     * @param actual Identificador de a pantalla.
     */
    private void bloquearBotonActual(String actual) {
            if (actual.equals("CLIENTES")) {
                btnClientes.setEnabled(false); 
            } 
            //Se modifica aqui cuando se agreguen los demas modulos
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnComandas;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel lbl2;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
