package com.mycompany.demabitespresentacion;

import com.mycompany.demabitesdtos.DetalleComandaDTO;
import com.mycompany.demabitesdtos.MesaDTO;
import com.mycompany.demabitesdtos.NuevaComandaDTO;
import com.mycompany.demabitesdtos.NuevoClienteFrecuenteDTO;
import com.mycompany.demabitesdtos.ProductoDTO;
import com.mycompany.demabitesutilidades.IBusqueda;
import control.MesasControl;
import control.Navegacion;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utileria.BusquedaProductos;

/**
 *
 * @author emyla
 */
public class NuevaComandaForm extends javax.swing.JFrame {

    private MesasControl mesasControl;
    private List<MesaDTO> listaMesasDisponibles;
    private NuevoClienteFrecuenteDTO clienteComanda;
    
    
    /**
     * Creates new form NuevaComandaForm
     */
    public NuevaComandaForm() {
        initComponents();
        mesasControl = new control.MesasControl();
        cargarMesasComboBox();
        
        btnBuscarCliente.setVisible(false);
        txtClienteNombre.setVisible(false);
        
        cbxCliente.addActionListener(e -> {
            // Validamos que haya un item seleccionado para evitar NullPointerException
            if (cbxCliente.getSelectedItem() != null) {
                String seleccion = cbxCliente.getSelectedItem().toString();
                if (seleccion.equals("Cliente frecuente")) {
                    btnBuscarCliente.setVisible(true); 
                } else {
                    btnBuscarCliente.setVisible(false); 
                    this.clienteComanda = null;
                }
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        cbxMesa = new javax.swing.JComboBox<>();
        lbl4 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        lbl5 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnCancelarComanda = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        txtClienteNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 255, 234));

        lbl2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 32)); // NOI18N
        lbl2.setForeground(new java.awt.Color(52, 59, 27));
        lbl2.setText("Nueva Comanda");

        lbl3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl3.setText("Número de mesa:");

        cbxMesa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl4.setText("Cliente:");

        cbxCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente general", "Cliente frecuente" }));

        lbl5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl5.setText("Productos:");

        btnBuscar1.setBackground(new java.awt.Color(47, 65, 86));
        btnBuscar1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("Agregar productos");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Producto", "Cantidad", "Comentario", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        lbl6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl6.setText("Total:");

        lbl7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl7.setText("$00.00");

        btnContinuar.setBackground(new java.awt.Color(47, 65, 86));
        btnContinuar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnCancelarComanda.setBackground(new java.awt.Color(158, 42, 43));
        btnCancelarComanda.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnCancelarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarComanda.setText("CANCELAR");
        btnCancelarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarComandaActionPerformed(evt);
            }
        });

        btnBuscarCliente.setBackground(new java.awt.Color(47, 65, 86));
        btnBuscarCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        txtClienteNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCliente, 0, 268, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl6)
                        .addGap(53, 53, 53)
                        .addComponent(lbl7)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnCancelarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnBuscarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCliente)
                .addGap(5, 5, 5)
                .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar1)
                    .addComponent(lbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6)
                    .addComponent(lbl7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnCancelarComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarComandaActionPerformed
        Navegacion.getControlNavegacion().abrirComandasFrame();
    }//GEN-LAST:event_btnCancelarComandaActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
       
        IBusqueda busquedaClientes = new utileria.BusquedaClientes(); 

        BuscadorDialog buscador = new BuscadorDialog(this, true, busquedaClientes);
        buscador.setVisible(true); 

        Object seleccion = buscador.getObjetoSeleccionado();

        if (seleccion != null) {
            try {
                NuevoClienteFrecuenteDTO clienteElegido = (NuevoClienteFrecuenteDTO) seleccion;

                String nombreCompleto = clienteElegido.getNombres() + " " + clienteElegido.getApellidoPaterno();
                txtClienteNombre.setText(nombreCompleto);
                txtClienteNombre.setEditable(false);

                this.clienteComanda = clienteElegido;

                txtClienteNombre.setVisible(true);            

                jPanel1.revalidate();
                jPanel1.repaint();

            } catch (ClassCastException e) {
                JOptionPane.showMessageDialog(this, "Error de tipo de dato", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        IBusqueda estrategiaProductos = new BusquedaProductos();
        
        BuscadorDialog buscador = new BuscadorDialog(this, true, estrategiaProductos);
        buscador.setVisible(true); 
        
        Object seleccion = buscador.getObjetoSeleccionado();
        
        if (seleccion != null) {
            ProductoDTO producto = (ProductoDTO) seleccion;
            
            String cantStr = JOptionPane.showInputDialog(this, 
                    "¿Qué cantidad de '" + producto.getNombre() + "' desea agregar?", 
                    "Cantidad", 
                    JOptionPane.QUESTION_MESSAGE);
            
            if (cantStr == null || cantStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "Operación cancelada: Debe ingresar una cantidad para agregar el producto.", 
                        "Aviso", 
                        JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            if (cantStr != null && !cantStr.trim().isEmpty()) {
                try {
                    int cantidad = Integer.parseInt(cantStr);
                    if (cantidad <= 0) {
                        JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
                        return;
                    }
                    
                    String comentario = JOptionPane.showInputDialog(this, 
                            "Comentarios para cocina: \n(Deje en blanco si no hay comentarios)", 
                            "Comentarios", 
                            JOptionPane.PLAIN_MESSAGE);
                    
                    if (comentario == null) comentario = "";

                    double subtotal = cantidad * producto.getPrecio();
                    
                    DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
                    modelo.addRow(new Object[]{
                        producto.getId(),
                        producto.getNombre(),
                        cantidad,
                        comentario,
                        "$" + String.format("%.2f", subtotal)
                    });

                    actualizarTotalComanda();
                    
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // Verificar que haya productos en la tabla
        if (jTable2.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un producto a la comanda.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verificar que se haya seleccionado una mesa
        if (cbxMesa.getSelectedIndex() == -1 || listaMesasDisponibles == null || listaMesasDisponibles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una mesa válida.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verificar cliente frecuente
        String tipoCliente = cbxCliente.getSelectedItem().toString();
        if (tipoCliente.equals("Cliente frecuente") && this.clienteComanda == null) {
            JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un cliente frecuente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Obtener la mesa seleccionada
            int mesaIndex = cbxMesa.getSelectedIndex();
            MesaDTO mesaSeleccionada = listaMesasDisponibles.get(mesaIndex);

            // Obtener el total (quitando el símbolo $ que agregaste en el label)
            String totalStr = lbl7.getText().replace("$", "").replace(",", "");
            double totalComanda = Double.parseDouble(totalStr);

            // Lista para guardar los detalles
            List<DetalleComandaDTO> detalles = new java.util.ArrayList<>();
            DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();

            for (int i = 0; i < modelo.getRowCount(); i++) {
                Long idProducto = Long.valueOf(modelo.getValueAt(i, 0).toString());

                String nombreProductoStr = modelo.getValueAt(i, 1).toString();

                int cantidad = Integer.parseInt(modelo.getValueAt(i, 2).toString());
                String comentario = modelo.getValueAt(i, 3).toString();

                String subtotalFilaStr = modelo.getValueAt(i, 4).toString().replace("$", "").replace(",", "");
                double subtotal = Double.parseDouble(subtotalFilaStr);
                
                ProductoDTO productoFila = new ProductoDTO();
                productoFila.setId(idProducto);
                
                DetalleComandaDTO detalle = new DetalleComandaDTO(idProducto, cantidad, subtotal, comentario, productoFila);
                detalles.add(detalle);
            }

            NuevaComandaDTO nuevaComanda = new NuevaComandaDTO();
            nuevaComanda.setMesa(mesaSeleccionada);
            nuevaComanda.setTotal(totalComanda);
            nuevaComanda.setDetalles(detalles);
            nuevaComanda.setFechaHora(LocalDateTime.now());

            if (tipoCliente.equals("Cliente frecuente")) {
                nuevaComanda.setCliente(this.clienteComanda);
            }

            control.ComandasControl comandasControl = new control.ComandasControl();
            
            comandasControl.registrarComanda(nuevaComanda, this);

            boolean guardadoExitoso = true;

            if (guardadoExitoso) {
                JOptionPane.showMessageDialog(this, "¡Comanda registrada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                Navegacion.getControlNavegacion().abrirComandasFrame();
                this.dispose(); 
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al procesar la comanda.", "Error Crítico", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * Carga las mesas disponibles desde la base de datos y las pone en el ComboBox.
     */
    private void cargarMesasComboBox() {
        // Obtenemos la lista de mesas
        listaMesasDisponibles = mesasControl.obtenerMesasDisponibles();
        
        if (listaMesasDisponibles != null && !listaMesasDisponibles.isEmpty()) {
            // Llenamos el ComboBox
            for (MesaDTO mesa : listaMesasDisponibles) {
                cbxMesa.addItem(mesa.toString()); // Automáticamente pondrá "Mesa X"
            }
        } else {
            // Si no hay mesas, bloqueamos el ComboBox y avisamos
            cbxMesa.addItem("No hay mesas disponibles");
            cbxMesa.setEnabled(false);
            btnContinuar.setEnabled(false); // Bloqueamos el botón de Continuar
        }
    }
    
    /**
     * Recorre la tabla de productos para sumar los subtotales y mostrar el Total.
     */
    private void actualizarTotalComanda() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        double total = 0.0;
        
        for (int i = 0; i < modelo.getRowCount(); i++) {
            // Sacamos el texto del subtotal
            String subtotalStr = modelo.getValueAt(i, 4).toString();
            // Le quitamos el signo de pesos para poder sumarlo
            subtotalStr = subtotalStr.replace("$", "").replace(",", "");
            total += Double.parseDouble(subtotalStr);
        }
        
        // Lo mostramos en la etiqueta
        lbl7.setText("$" + String.format("%.2f", total));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelarComanda;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxMesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JTextField txtClienteNombre;
    // End of variables declaration//GEN-END:variables
}
