package com.mycompany.demabitespresentacion;

import com.github.lgooddatepicker.components.DatePicker;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.logging.Logger;

/**
 *
 * @author Dario
 */
public class PanelFiltroComandas extends javax.swing.JPanel {

    private static final Logger LOGGER = Logger.getLogger(PanelFiltroComandas.class.getName());
    private DatePicker dpDesde;
    private DatePicker dpHasta;
    
    /**
     * Creates new form PanelFiltroComandas
     */
    public PanelFiltroComandas() {
        initComponents();
        dpDesde = new DatePicker();
        dpHasta = new DatePicker();
        
        // 3. Los agregamos a los paneles que pusiste en el diseño
        pnlDesde.setLayout(new BorderLayout());
        pnlDesde.add(dpDesde, BorderLayout.CENTER);
        
        pnlHasta.setLayout(new BorderLayout());
        pnlHasta.add(dpHasta, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        pnlDesde = new javax.swing.JPanel();
        pnlHasta = new javax.swing.JPanel();

        lbl16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lbl16.setText("Desde:");

        lbl17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lbl17.setText("Hasta:");

        javax.swing.GroupLayout pnlDesdeLayout = new javax.swing.GroupLayout(pnlDesde);
        pnlDesde.setLayout(pnlDesdeLayout);
        pnlDesdeLayout.setHorizontalGroup(
            pnlDesdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        pnlDesdeLayout.setVerticalGroup(
            pnlDesdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHastaLayout = new javax.swing.GroupLayout(pnlHasta);
        pnlHasta.setLayout(pnlHastaLayout);
        pnlHastaLayout.setHorizontalGroup(
            pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHastaLayout.setVerticalGroup(
            pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl17)
                    .addComponent(lbl16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Obtiene la fecha inicial seleccionada y le asigna la hora 00:00:00.
     * @return LocalDateTime con la fecha inicial, o null si está vacío/inválido.
     */
    public LocalDateTime getFechaInicio() {
        LocalDate fecha = dpDesde.getDate();
        if (fecha != null) {
            return fecha.atStartOfDay(); // Retorna a las 00:00:00
        }
        return null;
    }

    /**
     * Obtiene la fecha final seleccionada y le asigna la hora 23:59:59.
     * @return LocalDateTime con la fecha final, o null si está vacío/inválido.
     */
    public LocalDateTime getFechaFin() {
        LocalDate fecha = dpHasta.getDate();
        if (fecha != null) {
            return fecha.atTime(LocalTime.MAX); // Retorna a las 23:59:59
        }
        return null;
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JPanel pnlDesde;
    private javax.swing.JPanel pnlHasta;
    // End of variables declaration//GEN-END:variables
}
